stages:
  - test

hello-ci:
  stage: test
  image: alpine:latest
  script:
    - echo "CI/CD is working"
    - echo "Runner is $CI_RUNNER_DESCRIPTION"
    - echo "Project is $CI_PROJECT_PATH"
    - ls -la
